[package]
name = "ninja_doctor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minidom = "0.14.0"
zip = "0.6.2"
html-builder = "0.4.0"